//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiningRoomOrder
    {
        public int DOrderId { get; set; }
        public string DOrderFood { get; set; }
        public int DOrderQuantity { get; set; }
        public int DOrderDelete { get; set; }
    }
}
