//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int TrainingId { get; set; }
        public string TrainingName { get; set; }
        public string TrainingPosition { get; set; }
        public int DeleteTraining { get; set; }
    }
}
